### PR TITLE
Fix "Captoins" typo

### PR DESCRIPTION
**Pull request by tziporaziegler**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @tziporaziegler,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by tziporaziegler** [comment]
@kaltura-hooks I have no problem with you using my code changes under the CLA license. Is there though a way to contribute without having to provide personal information like email, phone number and address?

**Comment by jessp01** [comment]
Hi @tziporaziegler, I'm afraid due to legal considerations, we must have that info on record for all our contributors. I can assure you that info will not be shared with anyone outside the organisation and also that we shall never use them to spam your mailbox, however:)

**Comment by tziporaziegler** [comment]
@jessp01 That works for me :) I submitted a signed contract.

**Comment by jessp01** [comment]
@tziporaziegler - great, we got it:) @noamtamim - please merge.

**Pull request merged**
